### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ChasinSpin** [tkarabela/platesolve-polar-align#1]
Nice work. What license is it under?  (I'd like to use parts of it for an open source project).

**Comment by tkarabela** [comment]
Hi @ChasinSpin, I've updated the repository and added license - it's now in the public domain (just like https://github.com/ThemosTsikas/PhotoPolarAlign is).

So please use it as you will! I'd love to know what you end up doing with it, so feel free to share your project :)

**Comment by ChasinSpin** [comment]
Awesome!  Currently working on a project for Asteroid Occultation research (primarily) and as a general astrophotography device based on the Raspberry Pi.  Been in need of Polar Alignment and was struggling a bit with the math/process myself, yours was the first clear and complete description of the process.  I'll let you know when the project is uploaded to GitHub.
